# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2fa86fbf367db7b8b3a2e632bb1561e387d22abf3a76e4c5fe1db8d0e45e2bc6749bcd3264da65f5c6df56ac7f6c51c31f846e8c4c80030d2bffec31776bfdc

test:
  secret_key_base: f2176a5e37d16fb3082cfaa2ed73b2a6460d23437c7bb2875b3a00401eacab7979ad65ea1e0e8d7e9ecb3835f4ecf4ddb8903bc30b34257dda7ce90a3d25ec1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
